name: Manually Run Unit Tests

on:
  push:  # FIXME: temporarily for dev, generally remove when done
  pull_request:
  workflow_dispatch:
    
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: install htcondor
      run: pip3 install htcondor pyopenssl
      
    - name: run script
      run: python3 -m unittest discover --verbose --buffer  test
